# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: azfunc-openapi-on-root
infra:
    provider: "bicep"
    path: "infra"
    module: "main"
pipeline:
    provider: "github"
services:
  in-proc:
    project: "./src/InProc"
    host: "function"
    language: "dotnet"
    resourceName: "fncapp-swaggerui-in-proc"
  out-of-proc:
    project: "./src/OutOfProc"
    host: "function"
    language: "dotnet"
    resourceName: "fncapp-swaggerui-out-of-proc"
