name: 'Build, Test & Upload'

on:
  workflow_call:
    inputs:
      artifact_name:
        type: string
        required: false
        description: Artifact name of the function app
        default: fncapps

jobs:
  build_test_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x

    - name: Restore NuGet packages
      shell: bash
      run: |
        dotnet restore .

    - name: Build solution
      shell: bash
      run: |
        dotnet build . -c Release

    - name: Test solution
      shell: bash
      run: |
        dotnet test . -c Release

    - name: Create Function app artifacts
      shell: bash
      run: |
        dotnet publish src/InProc -c Release -o published/in-proc
        dotnet publish src/OutOfProc -c Release -o published/out-of-proc

    - name: Add Function app paths to env
      shell: pwsh
      run: |
        $published_path = "published"

        echo "PUBLISHED_PATH=$published_path" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append

    - name: Upload app artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ github.workspace }}/${{ env.PUBLISHED_PATH }}
        retention-days: 3
